import { Inter } from "next/font/google";
import "./globals.css";
import init from "@/config/config";
import ConfigLayout from "./ConfigLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
init();
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigLayout>{children}</ConfigLayout>
      </body>
    </html>
  );
}
